language: ruby
rvm:
  - 2.5.1

before_script:
  - chmod +x ./script/cibuild # or do this locally and commit

script: ./script/cibuild

sudo: false

cache: bundler

notifications:
  email: false

branches:
  except:
  - master
